#############################################################################
# Makefile for building: InvManager.app/Contents/MacOS/InvManager
# Generated by qmake (3.0) (Qt 5.2.0)
# Project:  InvManager.pro
# Template: app
# Command: /Users/Takatalvi/Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile InvManager.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_WIDGETS_LIB -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -gdwarf-2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/macx-clang -I. -I../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers -I../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtGui.framework/Versions/5/Headers -I../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -F/Users/Takatalvi/Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6
LIBS          = $(SUBLIBS) -F/Users/Takatalvi/Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework Foundation -framework QtSql -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /Users/Takatalvi/Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		adddialog.cpp \
		removedialog.cpp \
		preferences.cpp \
		dbhandler.cpp \
		updatedialog.cpp qrc_icons.cpp \
		moc_mainwindow.cpp \
		moc_adddialog.cpp \
		moc_removedialog.cpp \
		moc_preferences.cpp \
		moc_dbhandler.cpp \
		moc_updatedialog.cpp
OBJECTS       = main.o \
		mainwindow.o \
		adddialog.o \
		removedialog.o \
		preferences.o \
		dbhandler.o \
		updatedialog.o \
		qrc_icons.o \
		moc_mainwindow.o \
		moc_adddialog.o \
		moc_removedialog.o \
		moc_preferences.o \
		moc_dbhandler.o \
		moc_updatedialog.o
DIST          = ../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/spec_pre.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/qdevice.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/device_config.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/common/shell-unix.conf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/common/unix.conf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/common/mac.conf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/common/macx.conf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/common/gcc-base.conf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/common/clang.conf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/common/clang-mac.conf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/qconfig.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_clucene.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_designercomponents.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_platformsupport.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_quickparticles.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/qt_functions.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/qt_config.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/spec_post.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/default_pre.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/unix/default_pre.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/resolve_config.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/default_post.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/mac/sdk.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/mac/default_post.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/warn_on.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/qt.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/resources.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/moc.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/unix/opengl.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/uic.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/unix/thread.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/mac/rez.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/testcase_targets.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/exceptions.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/yacc.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/lex.prf \
		InvManager.pro \
		icons.qrc \
		InvManager.pro
QMAKE_TARGET  = InvManager
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = InvManager.app/Contents/MacOS/InvManager

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk \
		-mmacosx-version-min=10.6 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile InvManager.app/Contents/PkgInfo InvManager.app/Contents/Resources/empty.lproj InvManager.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_mainwindow.h ui_adddialog.h ui_removedialog.h ui_updatedialog.h $(OBJECTS)  
	@test -d InvManager.app/Contents/MacOS/ || mkdir -p InvManager.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: InvManager.pro ../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/macx-clang/qmake.conf ../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/spec_pre.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/qdevice.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/device_config.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/common/shell-unix.conf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/common/unix.conf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/common/mac.conf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/common/macx.conf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/common/gcc-base.conf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/common/clang.conf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/common/clang-mac.conf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/qconfig.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_clucene.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_designercomponents.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_platformsupport.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_quickparticles.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/qt_functions.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/qt_config.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/spec_post.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/default_pre.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/unix/default_pre.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/resolve_config.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/default_post.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/mac/sdk.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/mac/default_post.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/warn_on.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/qt.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/resources.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/moc.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/unix/opengl.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/uic.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/unix/thread.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/mac/rez.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/testcase_targets.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/exceptions.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/yacc.prf \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/lex.prf \
		InvManager.pro \
		icons.qrc \
		/Users/Takatalvi/Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/Takatalvi/Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/Takatalvi/Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/QtCore.prl \
		/Users/Takatalvi/Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/QtSql.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile InvManager.pro
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/spec_pre.prf:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/qdevice.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/device_config.prf:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/common/shell-unix.conf:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/common/unix.conf:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/common/mac.conf:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/common/macx.conf:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/common/gcc-base.conf:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/common/clang.conf:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/common/clang-mac.conf:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/qconfig.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_clucene.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_designercomponents.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_platformsupport.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_quickparticles.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/qt_functions.prf:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/qt_config.prf:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/macx-clang/qmake.conf:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/spec_post.prf:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/exclusive_builds.prf:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/default_pre.prf:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/unix/default_pre.prf:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/mac/default_pre.prf:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/resolve_config.prf:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/default_post.prf:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/mac/sdk.prf:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/mac/default_post.prf:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/mac/objective_c.prf:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/warn_on.prf:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/qt.prf:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/resources.prf:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/moc.prf:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/unix/opengl.prf:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/uic.prf:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/unix/thread.prf:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/mac/rez.prf:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/testcase_targets.prf:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/exceptions.prf:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/yacc.prf:
../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/features/lex.prf:
InvManager.pro:
icons.qrc:
/Users/Takatalvi/Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/Takatalvi/Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/Takatalvi/Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/QtCore.prl:
/Users/Takatalvi/Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/QtSql.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile InvManager.pro

qmake_all: FORCE

InvManager.app/Contents/PkgInfo: 
	@test -d InvManager.app/Contents || mkdir -p InvManager.app/Contents
	@$(DEL_FILE) InvManager.app/Contents/PkgInfo
	@echo "APPL????" >InvManager.app/Contents/PkgInfo
InvManager.app/Contents/Resources/empty.lproj: 
	@test -d InvManager.app/Contents/Resources || mkdir -p InvManager.app/Contents/Resources
	@touch InvManager.app/Contents/Resources/empty.lproj
	
InvManager.app/Contents/Info.plist: 
	@test -d InvManager.app/Contents || mkdir -p InvManager.app/Contents
	@$(DEL_FILE) InvManager.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,InvManager,g" -e "s,@TYPEINFO@,????,g" ../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/mkspecs/macx-clang/Info.plist.app >InvManager.app/Contents/Info.plist
dist: 
	@test -d .tmp/InvManager1.0.0 || mkdir -p .tmp/InvManager1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/InvManager1.0.0/ && $(COPY_FILE) --parents icons.qrc .tmp/InvManager1.0.0/ && $(COPY_FILE) --parents mainwindow.h adddialog.h removedialog.h inventoryItem.h preferences.h dbhandler.h updatedialog.h utility.h .tmp/InvManager1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp adddialog.cpp removedialog.cpp preferences.cpp dbhandler.cpp updatedialog.cpp .tmp/InvManager1.0.0/ && $(COPY_FILE) --parents mainwindow.ui adddialog.ui removedialog.ui updatedialog.ui .tmp/InvManager1.0.0/ && (cd `dirname .tmp/InvManager1.0.0` && $(TAR) InvManager1.0.0.tar InvManager1.0.0 && $(COMPRESS) InvManager1.0.0.tar) && $(MOVE) `dirname .tmp/InvManager1.0.0`/InvManager1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/InvManager1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r InvManager.app
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all: qrc_icons.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_icons.cpp
qrc_icons.cpp: icons.qrc \
		icons/up.png \
		icons/down.png
	/Users/Takatalvi/Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/bin/rcc -name icons icons.qrc -o qrc_icons.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_adddialog.cpp moc_removedialog.cpp moc_preferences.cpp moc_dbhandler.cpp moc_updatedialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_adddialog.cpp moc_removedialog.cpp moc_preferences.cpp moc_dbhandler.cpp moc_updatedialog.cpp
moc_mainwindow.cpp: ../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlDatabase \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldatabase.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlQuery \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquery.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlError \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlerror.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlQueryModel \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquerymodel.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QFileDialog \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QTextStream \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qtextstream.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QThread \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qthread.h \
		adddialog.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/QtSql \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsql.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriver.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriverplugin.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlfield.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlindex.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrecord.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlresult.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaldelegate.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaltablemodel.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqltablemodel.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qtsqlversion.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QListWidgetItem \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlistwidget.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		inventoryItem.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QStringList \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qstringlist.h \
		removedialog.h \
		updatedialog.h \
		preferences.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QMutex \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qmutex.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		dbhandler.h \
		utility.h \
		mainwindow.h
	/Users/Takatalvi/Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/usr/include/c++/4.2.1 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/usr/include/c++/4.2.1/backward -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/4.2/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_adddialog.cpp: ../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/QtSql \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsql.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldatabase.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriver.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriverplugin.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlerror.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlfield.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlindex.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquery.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrecord.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlresult.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquerymodel.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaldelegate.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaltablemodel.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqltablemodel.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qtsqlversion.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QListWidgetItem \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlistwidget.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		inventoryItem.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QStringList \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qstringlist.h \
		adddialog.h
	/Users/Takatalvi/Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/usr/include/c++/4.2.1 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/usr/include/c++/4.2.1/backward -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/4.2/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/usr/include adddialog.h -o moc_adddialog.cpp

moc_removedialog.cpp: ../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/QtSql \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsql.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldatabase.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriver.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriverplugin.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlerror.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlfield.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlindex.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquery.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrecord.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlresult.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquerymodel.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaldelegate.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaltablemodel.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqltablemodel.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qtsqlversion.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		inventoryItem.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QStringList \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qstringlist.h \
		removedialog.h
	/Users/Takatalvi/Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/usr/include/c++/4.2.1 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/usr/include/c++/4.2.1/backward -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/4.2/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/usr/include removedialog.h -o moc_removedialog.cpp

moc_preferences.cpp: ../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QThread \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qthread.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QMutex \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qmutex.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		preferences.h
	/Users/Takatalvi/Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/usr/include/c++/4.2.1 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/usr/include/c++/4.2.1/backward -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/4.2/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/usr/include preferences.h -o moc_preferences.cpp

moc_dbhandler.cpp: ../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QThread \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qthread.h \
		inventoryItem.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QStringList \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qstringlist.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/QtSql \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsql.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldatabase.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriver.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriverplugin.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlerror.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlfield.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlindex.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquery.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrecord.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlresult.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquerymodel.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaldelegate.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaltablemodel.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqltablemodel.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qtsqlversion.h \
		dbhandler.h
	/Users/Takatalvi/Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/usr/include/c++/4.2.1 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/usr/include/c++/4.2.1/backward -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/4.2/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/usr/include dbhandler.h -o moc_dbhandler.cpp

moc_updatedialog.cpp: ../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		updatedialog.h
	/Users/Takatalvi/Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/usr/include/c++/4.2.1 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/usr/include/c++/4.2.1/backward -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/4.2/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/usr/include updatedialog.h -o moc_updatedialog.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_adddialog.h ui_removedialog.h ui_updatedialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_adddialog.h ui_removedialog.h ui_updatedialog.h
ui_mainwindow.h: mainwindow.ui
	/Users/Takatalvi/Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_adddialog.h: adddialog.ui
	/Users/Takatalvi/Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/bin/uic adddialog.ui -o ui_adddialog.h

ui_removedialog.h: removedialog.ui
	/Users/Takatalvi/Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/bin/uic removedialog.ui -o ui_removedialog.h

ui_updatedialog.h: updatedialog.ui
	/Users/Takatalvi/Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/bin/uic updatedialog.ui -o ui_updatedialog.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlDatabase \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldatabase.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlQuery \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquery.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlError \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlerror.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlQueryModel \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquerymodel.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QFileDialog \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QTextStream \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qtextstream.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QThread \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qthread.h \
		adddialog.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/QtSql \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsql.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriver.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriverplugin.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlfield.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlindex.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrecord.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlresult.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaldelegate.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaltablemodel.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqltablemodel.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qtsqlversion.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QListWidgetItem \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlistwidget.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		inventoryItem.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QStringList \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qstringlist.h \
		removedialog.h \
		updatedialog.h \
		preferences.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QMutex \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qmutex.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		dbhandler.h \
		utility.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlDatabase \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldatabase.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlQuery \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquery.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlError \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlerror.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlQueryModel \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquerymodel.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QFileDialog \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QTextStream \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qtextstream.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QThread \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qthread.h \
		adddialog.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/QtSql \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsql.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriver.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriverplugin.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlfield.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlindex.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrecord.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlresult.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaldelegate.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaltablemodel.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqltablemodel.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qtsqlversion.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QListWidgetItem \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlistwidget.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		inventoryItem.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QStringList \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qstringlist.h \
		removedialog.h \
		updatedialog.h \
		preferences.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QMutex \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qmutex.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		dbhandler.h \
		utility.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

adddialog.o: adddialog.cpp adddialog.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/QtSql \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsql.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldatabase.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriver.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriverplugin.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlerror.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlfield.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlindex.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquery.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrecord.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlresult.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquerymodel.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaldelegate.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaltablemodel.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqltablemodel.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qtsqlversion.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QListWidgetItem \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlistwidget.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		inventoryItem.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QStringList \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qstringlist.h \
		ui_adddialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o adddialog.o adddialog.cpp

removedialog.o: removedialog.cpp removedialog.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/QtSql \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsql.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldatabase.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriver.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriverplugin.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlerror.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlfield.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlindex.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquery.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrecord.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlresult.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquerymodel.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaldelegate.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaltablemodel.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqltablemodel.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qtsqlversion.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		inventoryItem.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QStringList \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qstringlist.h \
		ui_removedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o removedialog.o removedialog.cpp

preferences.o: preferences.cpp preferences.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QThread \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qthread.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QMutex \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qmutex.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o preferences.o preferences.cpp

dbhandler.o: dbhandler.cpp dbhandler.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QThread \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qthread.h \
		inventoryItem.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/QStringList \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers/qstringlist.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/QtSql \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsql.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldatabase.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriver.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriverplugin.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlerror.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlfield.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlindex.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquery.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrecord.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlresult.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquerymodel.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaldelegate.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaltablemodel.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqltablemodel.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtSql.framework/Versions/5/Headers/qtsqlversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dbhandler.o dbhandler.cpp

updatedialog.o: updatedialog.cpp updatedialog.h \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		../../Development/Qt-5.2.0-android/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		ui_updatedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o updatedialog.o updatedialog.cpp

qrc_icons.o: qrc_icons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_icons.o qrc_icons.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_adddialog.o: moc_adddialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_adddialog.o moc_adddialog.cpp

moc_removedialog.o: moc_removedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_removedialog.o moc_removedialog.cpp

moc_preferences.o: moc_preferences.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_preferences.o moc_preferences.cpp

moc_dbhandler.o: moc_dbhandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dbhandler.o moc_dbhandler.cpp

moc_updatedialog.o: moc_updatedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_updatedialog.o moc_updatedialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

